context:
  version: "2.1.0"

package:
  name: hdf5
  version: ${{ version }}

build:
  script:
    file: ../conda-build.sh
    env:
      BUILD_DIR: build-tsan
      CFLAGS: "-fsanitize=thread"
      LDFLAGS: "-fsanitize=thread"

requirements:
  build:
    - clang
    - cmake
    - ninja
    - libaec  # for szip support
    - zlib
  host:
    - libaec  # for szip support
    - zlib
  run:
    - libcompiler-rt

about:
  homepage: https://www.hdfgroup.org/solutions/hdf5/
  license: BSD-3-Clause
  license_family: BSD
