name: build and test

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]
  workflow_dispatch: # allows you to trigger manually

defaults:
  run:
    shell: bash -l {0}

# When this workflow is queued, automatically cancel any previous running
# or pending jobs from the same branch
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest # x86-64
          - ubuntu-24.04-arm # ARM
          - macos-15-intel # x86-64
          - macos-latest # ARM
          # FIXME tests glitch on Windows in Debug mode
          # TODO need Windows-specific conda build script
          # - windows-latest  # x86-64

    steps:
      - name: Checkout hdf5-pixi
        uses: actions/checkout@v4

      - name: Checkout HDF5
        uses: actions/checkout@v4
        with:
          repository: HDFGroup/hdf5
          path: hdf5
          ref: develop

      - uses: prefix-dev/setup-pixi@v0
        with:
          pixi-version: v0.58.0
          environments: build conda-build

      - name: Build
        run: pixi run build

      - name: Test
        run: pixi run test

      - name: Pack
        run: pixi run pack

      - name: Upload Artifact
        uses: actions/upload-artifact@v5
        with:
          name: hdf5-pixi-${{ matrix.os }}
          path: build/HDF5-*

      - name: Build Conda Package
        run: pixi run conda-build

      - name: Upload Conda repository
        uses: actions/upload-artifact@v5
        with:
          name: hdf5-conda-${{ matrix.os }}
          path: conda-bld
